# Generated by Django 4.2.6 on 2023-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slocation', models.CharField(max_length=100)),
                ('sprincipal', models.CharField(max_length=100)),
            ],
        ),
    ]
